name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test and compile
      run: |
      
        cd "7"
        make 
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: |
          ./7/test.c.gcov
