name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Fetch
      uses: actions/checkout@master
    - uses: actions/checkout@v2
    - name: compile and test
      run: | 
        make
    - name: Upload
